---
title: ienze koekkoek - Verstaat
short_title: ikverstaat
lang: nl
image: "/assets/img/ikverstaat.png"
description: Opdrachtgevers vragen mij om in een landelijk gebied  bewoners, ondernemers
  (zoals agrariërs), organisaties en overheden te organiseren om gezamenlijk veranderingen
  in gang te zetten die nodig zijn voor een duurzame toekomst voor mens, milieu en
  economie.
cookie_text: Wij gebruiken cookies om ervoor te zorgen dat onze website zo soepel
  mogelijk draait.
timezone: Europe/Amsterdam
blauwe_accent_kleur: "#017bb2"
groene_accent_kleur: "#00675c"
gele_accent_kleur: "#fdee00"
rode_accent_kleur: "#da512c"
footer_background: "#343a40"
dribbble_username: ''
facebook_username: ''
flickr_username: ''
github_username: ''
instagram_username: ''
linkedin_username: ienze-koekkoek-9a4b0013
pinterest_username: ''
twitter_username: 'ikverstaat'
youtube_username: ''
telefoon: '+31 6 10596549'
email: i.koekkoek@ikverstaat.nl
logo: /assets/img/ikverstaat.png
author:
  twitter: ikverstaat
twitter:
  username: ikverstaat
  card: summary
social:
  name: IK Verstaat
  links:
    - https://twitter.com/ikverstaat
    - https://www.linkedin.com/in/ienze-koekkoek-9a4b0013
share:
- facebook
- twitter
- email
- linkedin
- whatsapp
collections:
  posts:
    output: true
defaults:
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
- scope:
    path: ''
  values:
    image: "/assets/img/logo.png"
    lang: nl
sass:
  style: compressed
  sass_dir: assets/_scss
url: https://ikverstaat.esstudio.site
enforce_ssl: ikverstaat.esstudio.site
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-sitemap
- jekyll-seo-tag
markdown: kramdown
google_analytics: UA-90014538-4
googleplus_username: 
