---
title: ienze koekkoek - Verstaat
short_title: ikverstaat
lang: nl
image: "/uploads/ikverstaat-cropped.png"
description: Opdrachtgevers vragen mij om in een landelijk gebied  bewoners, ondernemers
  (zoals agrariërs), organisaties en overheden te organiseren om gezamenlijk veranderingen
  in gang te zetten die nodig zijn voor een duurzame toekomst voor mens, milieu en
  economie.
cookie_text: Wij gebruiken cookies om ervoor te zorgen dat onze website zo soepel
  mogelijk draait.
timezone: Europe/Amsterdam
blauwe_accent_kleur: "#017bb2"
groene_accent_kleur: "#00675c"
gele_accent_kleur: "#fdee00"
rode_accent_kleur: "#da512c"
footer_background: "#343a40"
dribbble_username: ''
facebook_username: IK-Verstaat-675013529610491
flickr_username: ''
github_username: ''
instagram_username: ''
linkedin_username: ienze-koekkoek-9a4b0013
pinterest_username: ''
twitter_username: ikverstaat
youtube_username: ''
telefoon: "+31 6 10596549"
email: i.koekkoek@ikverstaat.nl
logo: "/uploads/ikverstaat-cropped.png"
humanstxt_author:
  role: Developer
  name: Sem Postma
  from: Oosterhout NB, The Netherlands
  email: sem.postma@gmail.com
humanstxt_designer:
  role: Designer
  name: Sem Postma
  from: Oosterhout NB, The Netherlands
  email: sem.postma@gmail.com
author:
  twitter: ikverstaat
facebook:
  app_id: 2397867613578443
  publisher: 100035254476963
  admins: 100035254476963
twitter:
  username: ikverstaat
  card: summary
social:
  name: IK Verstaat
  links:
  - https://twitter.com/ikverstaat
  - https://www.linkedin.com/in/ienze-koekkoek-9a4b0013
  - https://www.facebook.com/IK-Verstaat-675013529610491
share:
- facebook
- twitter
- email
- linkedin
- whatsapp
collections:
  posts:
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    image: "/uploads/ikverstaat-cropped.png"
    lang: nl
sass:
  style: compressed
  sass_dir: assets/_scss
url: https://ikverstaat.nl
enforce_ssl: ikverstaat.nl
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-sitemap
- jekyll-seo-tag
markdown: kramdown
google_analytics: UA-90014538-26
googleplus_username: 
