---
title: Echo Sierra Studio
timezone: Europe/Amsterdam
blauwe_accent_kleur: "#3f768a"
groene_accent_kleur: "#3b702a"
oranje_accent_kleur: "#f7a600"
dribbble_username: es_studio
facebook_username: ES-Studio-2052606714783317
flickr_username: es_studio
github_username: LesterGallagher
instagram_username: 
linkedin_username: 
pinterest_username: eestudio0040
twitter_username: esstudio_site
youtube_username: 9Wereld
telefoon: 0612345678
email: i.koekkoek@ikverstaat.nl

sass:
  style: compressed
  sass_dir: assets/_scss
url: https://ikverstaat.esstudio.site
enforce_ssl: ikverstaat.esstudio.site
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-sitemap
- jekyll-seo-tag
markdown: kramdown
google_analytics: UA-90014538-4
---