---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: "./_config.yml"
  label: config
  match: "**/*"
- type: document
  path: _data/menu.yml
  label: Navigatie Menu
- type: document
  path: _data/footer.yml
  label: Footer
- type: heading
  label: Pagina's
- type: document
  path: ervaring.md
  label: Ervaring
- type: document
  path: privacy-policy.md
  label: Privacy statement
- type: document
  path: terms-of-service.md
  label: Algemene voorwaarden
- type: document
  path: projecten.md
  label: Projecten
- type: document
  path: contact.md
  label: Contact
- type: document
  path: index.md
  label: Home
- type: document
  path: over.md
  label: Over
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
