---
label: config
hide_body: false
is_partial: false
fields:
- name: title
  label: Titel
  type: text
  hidden: false
  default: ''
  description: De titel van de website
  config:
    required: true
- name: short_title
  label: Korte titel
  type: text
  hidden: false
  default: ''
  description: Een korte titel (max. 12 tekens)
  config:
    required: true
- name: Afbeelding
  label: Image
  type: file
  hidden: false
  default: ''
  description: Standaard afbeelding van de website. Dit zien mensen wanneer ze je
    website delen op facebook bijvoorbeeld.
- name: description
  label: Beschrijving
  type: textarea
  hidden: false
  default: ''
  description: Een korte uitleg over de website.
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
- name: cookie_text
  label: Cookie tekst
  type: text
  hidden: false
  default: ''
  description: De tekst van de cookie vermelding
  config:
    required: true
- name: timezone
  label: Timezone
  type: text
  hidden: true
  default: ''
  config:
    required: true
- name: blauwe_accent_kleur
  label: Blauwe accent kleur
  type: color
  hidden: false
  default: ''
  config:
    color_format: Hex
    required: true
  description: De blauwe kleur op de website.
- name: groene_accent_kleur
  label: Groene accent kleur
  type: color
  hidden: false
  default: ''
  config:
    color_format: Hex
    required: true
  description: De groene kleur op de website
- name: gele_accent_kleur
  label: Gele accent kleur
  type: color
  hidden: false
  default: ''
  config:
    color_format: Hex
    required: true
  description: De gele kleur op de website
- name: rode_accent_kleur
  label: Rode accent kleur
  type: color
  hidden: false
  default: ''
  config:
    color_format: Hex
    required: true
  description: De rode kleur op de website
- name: footer_background
  label: Footer actergrond kleur
  type: color
  hidden: false
  default: ''
  config:
    color_format: Hex
    required: true
  description: De achtergrond kleur van de footer (het onderste gedeelte van de website).
- name: dribbble_username
  label: Dribbble gebruikersnaam
  type: text
  hidden: false
  default: ''
- name: facebook_username
  label: Facebook gebruikersnaam
  type: text
  hidden: false
  default: ''
- name: flickr_username
  label: Flickr gebruikersnaam
  type: text
  hidden: false
  default: ''
- name: github_username
  label: Github gebruikersnaam
  type: text
  hidden: false
  default: ''
- name: linkedin_username
  label: Linkedin gebruikersnaam
  type: text
  hidden: false
  default: ''
- name: instagram_username
  label: Instagram gebruikersnaam
  type: text
  hidden: false
  default: ''
- name: pinterest_username
  label: Pinterest gebruikersnaam
  type: text
  hidden: false
  default: ''
- name: twitter_username
  label: Twitter gebruikersnaam
  type: text
  hidden: false
  default: ''
- name: youtube_username
  label: Youtube gebruikersnaam
  type: text
  hidden: true
  default: ''
- name: telefoon
  label: Telefoon
  type: text
  hidden: false
  default: ''
- name: email
  label: Email
  type: text
  hidden: false
  default: ''
- name: share
  label: Share
  type: list
  hidden: false
  default: []
- name: lang
  label: Lang
  type: text
  hidden: false
  default: ''
- name: defaults
  label: Defaults
  type: field_group_list
  fields:
  - name: scope
    label: Scope
    type: field_group
    fields:
    - name: path
      label: Path
      type: text
      hidden: false
      default: ''
    hidden: false
    default: ''
  - name: values
    label: Values
    type: field_group
    fields:
    - name: image
      label: Image
      type: file
      hidden: false
      default: ''
    hidden: false
    default: ''
  hidden: true
  default: ''
- name: sass
  label: Sass
  type: field_group
  fields:
  - name: style
    label: Style
    type: text
    hidden: false
    default: ''
  - name: sass_dir
    label: Sass dir
    type: text
    hidden: false
    default: ''
  hidden: true
  default: ''
- name: url
  label: Url
  type: text
  hidden: true
  default: ''
- name: enforce_ssl
  label: Enforce ssl
  type: text
  hidden: true
  default: ''
- name: plugins
  label: Plugins
  type: list
  hidden: true
  default: ''
- name: markdown
  label: Markdown
  type: text
  hidden: true
  default: ''
- name: google_analytics
  label: Google analytics
  type: text
  hidden: false
  default: ''
